### ISSUE TITLE
 how to configure?

### ISSUE THREAD

**Issue by raiokocha** [sentinel-hub/SentinelPlayground#5]
where do I put my key API? and where do I put my token?

**Comment by markneilpascual** [comment]
where do I put my key API? and where do I put my token?

**Comment by zcernigoj** [comment]
Hey, 

Similar [question](https://forum.sentinel-hub.com/t/sentinel-playground-app-api-key/3104) popped up a few days ago on our forum. So, most of the answer is from there, but I will add the info about the token location.

Sentinel Playground code here hasn’t been updated in quite some time, so there are some things that don't work out of the box.

The token would go into the [/public/tokenAssisted.html](https://github.com/sentinel-hub/SentinelPlayground/blob/master/public/tokenAssisted.html#L25), but at the moment, this user authentication mechanism is not available for general public use. 

One option to fix it yourself is that you remove all `AuthWindow` and `recaptchaAuthToken` authentication and replace it with a call to `requestAuthToken()` from `sentinelhub-js` (parameters are `clientId` and `clientSecret` which you can get from the SH Dashboard), followed by a call to `setAuthToken`.

Alternatively, you can use [sentinelhub-js](https://github.com/sentinel-hub/sentinelhub-js/) and [react-leaflet](https://react-leaflet.js.org/) (for example) to build a similar application from ground up, which also shouldn't be difficult to do.

If you have some more questions, the best place to ask is the forum (we generally answer faster there).

Best, Ziga

**Comment by zcernigoj** [comment]
I will close this issue for now in favour of forum questions.
